from datetime import datetime, timezone
from app import models
from app.utils import logger

from ._client import get_client
from ._collection import create_collection


_OUTPUT_FIELDS = [
    "doc_id",
    "title",
    "author_info",
    "tags",
    "metadata",
    "text",
    "dense_vector",
    "sparse_vector",
    "created_at",
    "updated_at",
]


def _doc_to_entity(doc: models.Document) -> dict:
    payload = doc.model_dump()

    # TIMESTAMPTZ fields are passed as strings by PyMilvus.
    payload["created_at"] = (doc.created_at).isoformat()
    payload["updated_at"] = (doc.updated_at or datetime.now(timezone.utc)).isoformat()

    # `sparse_vector` is generated by the BM25 function defined in the collection schema.
    # Supplying it during insert/upsert is rejected by Milvus.
    payload.pop("sparse_vector", None)
    return payload


def upsert_documents(docs: list[models.Document], collection_name: str) -> None:
    client = get_client()
    create_collection(collection_name)

    data = [_doc_to_entity(d) for d in docs]
    res = client.upsert(collection_name, data)
    logger.info(
        f"Upserted {res.get('upsert_count', 0)} documents into '{collection_name}'."
    )

    client.flush(collection_name)


def delete_documents(doc_ids: list[int], collection_name: str) -> int:
    if not doc_ids:
        return 0

    client = get_client()
    if not client.has_collection(collection_name):
        return 0

    res = client.delete(collection_name, ids=doc_ids)
    client.flush(collection_name)
    return int(res.get("delete_count", 0))
